apiVersion: batch/v1
kind: Job
metadata:
  name: cleanup
spec:
      template:
        spec:
          serviceAccountName: helm-traefik
          automountServiceAccountToken: false
          containers:
          - name: kubectl-runner
            image: wernight/kubectl
            command: ["sh", "-c", "kubectl get clusterrole"]
          restartPolicy: Never
