---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: toolbox-sa
  namespace: mpo

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
 name: toolbox-cluster-role
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
 name: toolbox-cluster-rolebinding
roleRef:
 apiGroup: rbac.authorization.k8s.io
 kind: ClusterRole
 name: toolbox-cluster-role
subjects:
- kind: ServiceAccount
  name: toolbox-sa
  namespace: mpo

---
kind: ConfigMap 
apiVersion: v1 
metadata:
  name: toolbox-cm
  namespace: mpo
data:
  cleanup.sh: | 
    #!/bin/bash

    kubectl get clusterrole
    kubectl get deployments -n kube-system

---
apiVersion: batch/v1
kind: Job
metadata:
  name: cleanup
  namespace: mpo
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
      backoffLimit: 0
      template:
        spec:
          serviceAccountName: toolbox-sa
          automountServiceAccountToken: true
          containers:
          - name: toolbox
            image: registry.gitlab.com/mambucom/product/ecosystem/mpo/toolbox/kubectl-helm-git:0.0.1
            command: ["/app/cleanup.sh"]
            volumeMounts:
             - name: config-volume
               mountPath: /app/cleanup.sh
               subPath: cleanup.sh
          volumes:
           - name: config-volume
             configMap:
               name: toolbox-cm
               defaultMode: 0777
          restartPolicy: Never
